import { ISpikeProps } from '../../shared/spike';

export const spikeConfig: ISpikeProps = {
    spikeName: 'Readspike Funny',
    spikeShortName: 'funny',
    spikeTitle: 'Simple news aggregator',
    spikeDescription: 'Aggregating the lols from around the web every minute',
    spikeHeaderBG: '#3D9970',
    spikeBodyBG: '#1e1d1f',
    spikeUrl: 'https://readspike.com/funny/',
    sectionConfig: [
        {
            'name': 'TheOnion',
            'title': 'The Onion',
            'type': 'xml',
            'color': '#006b3a',
            'col': '1',
            'row': '0',
            'mob': '1',
            'url': 'http://www.theonion.com/',
            'feed': 'http://www.theonion.com/feeds/rss',
        },
        {
            'name': 'Reddit',
            'title': 'Reddit Funny',
            'type': 'json',
            'color': '#ff4500',
            'col': '3',
            'row': '0',
            'mob': '0',
            'url': 'https://www.reddit.com/r/funny/',
            'feed': 'https://www.reddit.com/r/funny/.json?limit=100',
        },
        {
            'name': 'Buzzfeed',
            'title': 'Buzzfeed',
            'type': 'xml',
            'color': '#ee3322',
            'col': '2',
            'row': '0',
            'mob': '2',
            'url': 'https://www.buzzfeed.com/',
            'feed': 'https://www.buzzfeed.com/lol.xml',
        },
        {
            'name': 'Pinboard',
            'title': 'Pinboard Funny',
            'type': 'json',
            'color': '#5a80f2',
            'col': '1',
            'row': '5',
            'mob': '12',
            'url': 'https://www.pinboard.in/t:funny/',
            'feed': 'https://feeds.pinboard.in/json/t:funny/',
        },
        {
            'name': 'DailyMash',
            'title': 'The Daily Mash',
            'type': 'xml',
            'color': '#8a8a8a',
            'col': '2',
            'row': '1',
            'mob': '4',
            'url': 'http://www.thedailymash.co.uk/',
            'feed': 'http://www.thedailymash.co.uk/feed',
        },
        {
            'name': 'Waterford',
            'title': 'Waterford Whispers',
            'type': 'xml',
            'color': '#D52527',
            'col': '1',
            'row': '2',
            'mob': '12',
            'url': 'http://waterfordwhispersnews.com/',
            'feed': 'http://waterfordwhispersnews.com/feed/',
        },
        {
            'name': 'Newsthump',
            'title': 'Newsthump',
            'type': 'xml',
            'color': '#A51306',
            'col': '2',
            'row': '0',
            'mob': '6',
            'url': 'http://newsthump.com/',
            'feed': 'http://newsthump.com/feed/',
        },
        {
            'name': 'Fark',
            'title': 'Fark',
            'type': 'xml',
            'color': '#3d3daf',
            'col': '3',
            'row': '7',
            'mob': '11',
            'url': 'http://www.fark.com/',
            'feed': 'http://www.fark.com/fark.rss',
        },
        {
            'name': 'Cracked',
            'title': 'Cracked',
            'type': 'xml',
            'color': '#F4CE00',
            'col': '3',
            'row': '1',
            'mob': '10',
            'url': 'http://cracked.com/',
            'feed': 'http://feeds.feedburner.com/CrackedRSS',
        },
        {
            'name': 'ThePoke',
            'title': 'The Poke',
            'type': 'xml',
            'color': '#bb0016',
            'col': '2',
            'row': '3',
            'mob': '7',
            'url': 'http://www.thepoke.co.uk/',
            'feed': 'http://www.thepoke.co.uk/feed/',
        },
        {
            'name': 'TheChive',
            'title': 'The Chive',
            'type': 'xml',
            'color': '#339933',
            'col': '1',
            'row': '4',
            'mob': '9',
            'url': 'http://www.thechive.com/',
            'feed': 'http://feeds.feedburner.com/feedburner/ZdSV',
        }
    ]
};
