import { ISpikeProps } from '../../shared/spike';

export const spikeConfig: ISpikeProps = {
    spikeName: 'Readspike WebDev',
    spikeShortName: 'webdev',
    spikeTitle: 'Simple news aggregator',
    spikeDescription: 'Aggregating all the webdev news every minute',
    spikeHeaderBG: '#2ECC40',
    spikeBodyBG: '#1e1d1f',
    spikeUrl: 'https://readspike.com/webdev/',
    sectionConfig: [
        {
            'name': 'Reddit',
            'title': 'Reddit WebDev',
            'type': 'json',
            'color': '#ff4500',
            'col': '3',
            'row': '0',
            'mob': '0',
            'url': 'https://www.reddit.com/r/webdev/',
            'feed': 'https://www.reddit.com/r/webdev/.json?limit=100',
        },
        {
            'name': 'Pinboard',
            'title': 'Pinboard WebDev',
            'type': 'json',
            'color': '#5a80f2',
            'col': '1',
            'row': '5',
            'mob': '12',
            'url': 'https://www.pinboard.in/t:webdev/',
            'feed': 'https://feeds.pinboard.in/json/t:webdev/',
        },
        {
            'name': 'CSStricks',
            'title': 'CSS Tricks',
            'type': 'xml',
            'color': '#e18728',
            'col': '1',
            'row': '0',
            'mob': '5',
            'url': 'https://css-tricks.com/',
            'feed': 'http://feeds.feedburner.com/CssTricks',
        },
        {
            'name': 'DesignerNews',
            'title': 'Designer News',
            'type': 'xml',
            'color': '#2d72d9',
            'col': '2',
            'row': '0',
            'mob': '6',
            'url': 'https://www.designernews.co/',
            'feed': 'https://www.designernews.co/?format=rss',
        },
        {
            'name': 'WebDesignerNews',
            'title': 'Web Designer News',
            'type': 'xml',
            'color': '#fa5f66',
            'col': '2',
            'row': '0',
            'mob': '6',
            'url': 'http://www.webdesignernews.com/',
            'feed': 'http://feeds.feedburner.com/webdesignernews',
        },
        {
            'name': '456bereastreet',
            'title': '456 Berea Street',
            'type': 'xml',
            'color': '#e18728',
            'col': '3',
            'row': '6',
            'mob': '15',
            'url': 'http://www.456bereastreet.com/',
            'feed': 'http://feeds.feedburner.com/456bereastreet',
        },
        {
            'name': 'DZone',
            'title': 'DZone',
            'type': 'xml',
            'color': '#27B3F0',
            'col': '2',
            'row': '8',
            'mob': '12',
            'url': 'http://dzone.com/',
            'feed': 'http://feeds.dzone.com/webdev',
        },
        {
            'name': 'WebdesignerDepot',
            'title': 'WebdesignerDepot',
            'type': 'xml',
            'color': '#fab23a',
            'col': '2',
            'row': '3',
            'mob': '5',
            'url': 'http://www.webdesignerdepot.com/',
            'feed': 'http://feeds2.feedburner.com/webdesignerdepot',
        },
        {
            'name': 'WebDesignLedger',
            'title': 'Web Design Ledger',
            'type': 'xml',
            'color': '#27D3F5',
            'col': '2',
            'row': '3',
            'mob': '7',
            'url': 'https://webdesignledger.com/',
            'feed': 'https://webdesignledger.com/feed/',
        },
        {
            'name': 'SmashingMagazine',
            'title': 'Smashing Magazine',
            'type': 'xml',
            'color': '#E43B2C',
            'col': '1',
            'row': '2',
            'mob': '3',
            'url': 'https://smashingmagazine.com/',
            'feed': 'http://www.smashingmagazine.com/feed/'
        },
        {
            'name': 'CooperPress',
            'title': 'Cooper Press',
            'type': 'xml',
            'color': '#00aeef',
            'col': '2',
            'row': '6',
            'mob': '8',
            'url': 'https://cooperpress.com/',
            'feed': 'http://frontendfocus.co/rss/25k167j1',
        },
        {
            'name': 'PHPied',
            'title': 'PHPied',
            'type': 'xml',
            'color': '#3980c0',
            'col': '2',
            'row': '7',
            'mob': '11',
            'url': 'http://www.phpied.com/',
            'feed': 'http://www.phpied.com/feed/',
        },
        {
            'name': 'Scotch',
            'title': 'Scotch.io',
            'type': 'xml',
            'color': '#5D1624',
            'col': '1',
            'row': '1',
            'mob': '4',
            'url': 'https://scotch.io/',
            'feed': 'https://scotch.io/feed',
        },
        {
            'name': 'HTML5rocks',
            'title': 'HTML5 Rocks',
            'type': 'xml',
            'color': '#5fa49f',
            'col': '3',
            'row': '3',
            'mob': '8',
            'url': 'https://www.html5rocks.com/en/',
            'feed': 'http://feeds.feedburner.com/html5rocks',
        },
        {
            'name': 'HTML5doctor',
            'title': 'HTML5 Doctor',
            'type': 'xml',
            'color': '#0090D2',
            'col': '3',
            'row': '14',
            'mob': '15',
            'url': 'http://html5doctor.com/',
            'feed': 'http://feeds2.feedburner.com/html5doctor',
        },
        {
            'name': 'Quirksmode',
            'title': 'Quirksmode',
            'type': 'xml',
            'color': '#475D9B',
            'col': '1',
            'row': '4',
            'mob': '9',
            'url': 'http://www.quirksmode.org/blog/',
            'feed': 'http://www.quirksmode.org/blog/index.xml',
        },
        {
            'name': 'CSSwizardry',
            'title': 'CSS Wizardry',
            'type': 'xml',
            'color': '#f43059',
            'col': '2',
            'row': '5',
            'mob': '10',
            'url': 'http://csswizardry.com/',
            'feed': 'http://feeds.feedburner.com/csswizardry',
        },
        {
            'name': '24ways',
            'title': '24 Ways',
            'type': 'xml',
            'color': '#ff0040',
            'col': '3',
            'row': '5',
            'mob': '10',
            'url': 'https://24ways.org/',
            'feed': 'http://feeds.feedburner.com/24ways',
        },
        {
            'name': 'Alistapart',
            'title': 'A list Apart',
            'type': 'xml',
            'color': '#A7491C',
            'col': '2',
            'row': '2',
            'mob': '8',
            'url': 'http://alistapart.com/',
            'feed': 'http://alistapart.com/main/feed',
        },
        {
            'name': 'frontendfront',
            'title': 'Front-end Front',
            'type': 'xml',
            'color': '#2DBF80',
            'col': '2',
            'row': '0',
            'mob': '5',
            'url': 'https://frontendfront.com/',
            'feed': 'https://frontendfront.com/feed/stories',
        },
        {
            'name': 'Sitepoint',
            'title': 'Sitepoint',
            'type': 'xml',
            'color': '#8899a6',
            'col': '2',
            'row': '1',
            'mob': '3',
            'url': 'https://www.sitepoint.com/',
            'feed': 'https://www.sitepoint.com/feed/',
        },
        {
            'name': 'GoogleWebDev',
            'title': 'Google Web Developers',
            'type': 'xml',
            'color': '#4285f4',
            'col': '3',
            'row': '3',
            'mob': '9',
            'url': 'https://developers.google.com/web/',
            'feed': 'https://developers.google.com/web/updates/rss.xml',
        }
    ]
};
